### Bert Introduction

In [27]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text


In [2]:
ecoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

Working on the preprocessor layer

In [3]:
preprocess_model = hub.KerasLayer(preprocess_url)


In [6]:
text_test = ['nice movie by Keanu reeves', 'I loved his action style']
text_processed = preprocess_model(text_test)

In [7]:
text_processed.keys()
# contain differenent individual elemnts 


dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [8]:
text_processed['input_type_ids']
text_processed['input_mask']

# here sentence 'nice movie by Keanu reeves'contain 4 words but masks contain 7 words
# why is that
# inserting special token called CLS in the startthen sentence 'nice movie by Keanu reeves' then token SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [9]:
# checking the words id's 
text_processed['input_word_ids']

# CLS word id's for the first 5 words SEP
# for CLS id is 101, for SEP id is 102

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  2011, 17710, 24076, 17891,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

Working on the Encoder URL

In [10]:
ecoder_model  = hub.KerasLayer(ecoder_url)
bert_result = ecoder_model(text_processed)
bert_result.keys()

dict_keys(['default', 'encoder_outputs', 'pooled_output', 'sequence_output'])

In [11]:
bert_result['pooled_output']
# 2 is the num of sentences and 768 is the size of vector 

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8839981 , -0.38313437, -0.4424921 , ..., -0.16259381,
        -0.60588974,  0.86381143],
       [-0.68174195, -0.11061211,  0.5048464 , ...,  0.16292155,
        -0.4290835 ,  0.66700864]], dtype=float32)>

In [14]:
bert_result['pooled_output']
# len(bert_result['pooled_output'])
# len is 12 because we are using bert base small

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8839981 , -0.38313437, -0.4424921 , ..., -0.16259381,
        -0.60588974,  0.86381143],
       [-0.68174195, -0.11061211,  0.5048464 , ...,  0.16292155,
        -0.4290835 ,  0.66700864]], dtype=float32)>

In [13]:
bert_result['sequence_output']
# 128 is the padding around sentence output


<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-2.07256079e-01, -1.29273385e-01, -4.67188358e-01, ...,
         -3.66513669e-01,  2.86079943e-01,  3.79709035e-01],
        [ 1.00086674e-01, -4.42238271e-01,  5.45137763e-01, ...,
         -1.45009816e-01,  3.73329893e-02,  1.13097601e-01],
        [-5.48368320e-04, -2.99673110e-01, -1.48578689e-01, ...,
         -7.22971484e-02,  2.96550281e-02, -4.14181620e-01],
        ...,
        [-8.06599781e-02, -1.20575994e-01,  3.28488886e-01, ...,
          1.82476193e-01,  8.32296684e-02,  1.37455866e-01],
        [ 3.66917849e-02, -7.95436352e-02,  3.15790415e-01, ...,
          1.21758312e-01,  1.14292935e-01,  1.90111354e-01],
        [-4.62826937e-02, -3.61344814e-02,  3.64174277e-01, ...,
          1.82605520e-01,  8.24149400e-02,  1.79387704e-01]],

       [[-1.80836357e-02, -1.55743286e-01, -3.26163322e-03, ...,
         -2.27583379e-01,  1.49570614e-01, -5.17502576e-02],
        [ 3.32445353e-01, -1.94762915e-01, -5.32

In [16]:
len(bert_result['sequence_output'])


2

In [19]:
bert_result['sequence_output'] == bert_result['encoder_outputs'] [-1]
# last item of encoder output is same as sequence_output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

### Text Classification by Bert


Email Classification spam or not spam

In [ ]:
# bert can convert email classification to embedded vector

In [29]:
import pandas as pd

In [36]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [35]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [38]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head(5)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [55]:
# Lets apply train & test on this data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['Message'], df['spam'], test_size = 0.2, stratify = df['spam']) # stratify is for balance dataset of xtest and ytest 

In [43]:
len(x_train)

4457

In [56]:
x_train.value_counts()
x_test.value_counts()

y_test.value_counts()

0    966
1    149
Name: spam, dtype: int64

In [53]:
y_train.value_counts()

0    3846
1     611
Name: spam, dtype: int64

In [57]:
# spam ratio
611/ 3846
# 15 % of spam in train data

0.15886635465418616

In [63]:
def get_sentence_embedding(sentences):
    preprocess_text = preprocess_model(sentences)
    return ecoder_model(preprocess_text)['pooled_output']
    

In [65]:
get_sentence_embedding([
    "400$ discount, book it todays",
    "Asim are you ready to depart for Lahore Tommorow?"
])

# size is 768

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.71316993, -0.3180655 , -0.58051157, ..., -0.4214854 ,
        -0.6855236 ,  0.8428304 ],
       [-0.8966491 , -0.5084667 , -0.9310435 , ..., -0.8015126 ,
        -0.69806725,  0.9026503 ]], dtype=float32)>

In [70]:
# comparing the words using cosine similarity
e = get_sentence_embedding([
    'mango',
    'grapes',
    'Asim',
    'Dua'
])


In [74]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]], [e[3]])

# word1 and 2 is 98% similar
# word1 and 4 is 91% similar


array([[0.9156048]], dtype=float32)

check about sequential and functional models


In [81]:
# Lets use functional model
text_input = tf.keras.layers.Input(shape = ( ), dtype = tf.string, name = 'text')
preprocess_text = preprocess_model(text_input)
output = ecoder_model(preprocess_text)
# output['pooled_output']

drop_layer = tf.keras.layers.Dropout(0.1, name = 'dropout')(output['pooled_output'])
dense_layer =  tf.keras.layers.Dense(1, activation = 'sigmoid')(drop_layer)

# creating model for the traing
model = tf.keras.Model(inputs = [text_input], outputs = [dense_layer] )
model.summary()

# Trainable params: 769(768 + 1(dropout layer) )

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
text (InputLayer)               [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_mask': (None 0           text[0][0]                       
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'default': (None, 7 109482241   keras_layer[3][0]                
                                                                 keras_layer[3][1]                
                                                                 keras_layer[3][2]                
____________________________________________________________________________________________

In [85]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs = 5)

In [ ]:
model.evaluate(x_test, y_test)