In [1]:
import numpy as np

In [3]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [9]:
# first calculate mean absolute error
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
        print("Total error value is: ",total_error)
        mae = total_error/ len(y_true)
        print("Mean absolute error is: ", mae)
        
        return mae
#         print(yt, yp) #simply print values

In [10]:
mae(y_true, y_predicted)
# it just iterate over all true and predicted values

Total error value is:  0.7
Mean absolute error is:  0.13999999999999999


0.13999999999999999

In [11]:
# Numpy provide the real benifit of subtractions
# instead of for loop in zip we can simply use this
y_predicted- y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [13]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [15]:
np.sum(y_predicted - y_true)

0.5

In [18]:
np.mean(np.abs(y_predicted - y_true))

# IT CAN DO ALL STUFF OF CELL THREE(3) IN ONE LINE

0.5

In [19]:
np.sum(np.abs(y_predicted - y_true))
# total_error

2.5

In [22]:
# MEAN SQUARE ERROR 
np.mean(np.abs(np.square(y_predicted - y_true)))


0.366

In [23]:
# Binary classification or log Loss

In [25]:
# In binary log predicted value should be near to 1 but not 1 

In [29]:
y_predicted

array([1, 1, 0, 0, 1])

In [27]:
epsilon = 1e-15 # 1e-15 means 0.00000000000001

In [28]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

# Here it replaced value 0 with value very close to 1 

[1, 1, 1e-15, 1e-15, 1]

In [30]:
# Replace the value 1 which is very close to value 1 but not 1 
y_predicted_new = [min(i, 1- epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [33]:
# Converting all this new values into numoy array
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [35]:
# comparing the origional values with log values
print(np.log(y_predicted))
print(np.log(y_predicted_new))


[  0.   0. -inf -inf   0.]
[-9.99200722e-16 -9.99200722e-16 -3.45387764e+01 -3.45387764e+01
 -9.99200722e-16]


<ipython-input-35-2e54fb129840>:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(y_predicted))


In [37]:
# applying binary cross entropy
-np.mean(y_true * np.log(y_predicted_new) + (1- y_true)* np.log(1 - y_predicted_new))

17.2696280766844

In [40]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1- epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1- y_true)* np.log(1 - y_predicted_new))
    
    
    

In [41]:
log_loss(y_true, y_predicted)

17.2696280766844